AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  GraphQL:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.graphqlHandler
      Runtime: nodejs12.x
      Events:
        AnyRequest:
          Type: Api
          Properties:
            Path: /graphql
            Method: ANY
      CodeUri: s3://brandonvio-re-demo-api/1e920558e53effececea291b65b00e00
  GraphQLInspector:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.graphiqlHandler
      Runtime: nodejs12.x
      Events:
        AnyRequest:
          Type: Api
          Properties:
            Path: /graphiql
            Method: ANY
      CodeUri: s3://brandonvio-re-demo-api/1e920558e53effececea291b65b00e00
